## Pandas

In [1]:
import numpy as np
import pandas as pd

### Upload file in Colab

In [2]:
from google.colab import files
files.upload()

Saving student.csv to student.csv

{'student.csv': b'id,name,class,mark,gender\r\n1,John Deo,Four,75,female\r\n2,Max Ruin,Three,85,male\r\n3,Arnold,Three,55,male\r\n4,Krish Star,Four,60,female\r\n5,John Mike,Four,60,female\r\n6,Alex John,Four,55,male\r\n7,My John Rob,Fifth,78,male\r\n8,Asruid,Five,85,male\r\n9,Tes Qry,Six,78,male\r\n10,Big John,Four,55,female\r\n11,Ronald,Six,89,female\r\n12,Recky,Six,94,female\r\n13,Kty,Seven,88,female\r\n14,Bigy,Seven,88,female\r\n15,Tade Row,Four,88,male\r\n16,Gimmy,Four,88,male\r\n17,Tumyu,Six,54,male\r\n18,Honny,Five,75,male\r\n19,Tinny,Nine,18,male\r\n20,Jackly,Nine,65,female\r\n21,Babby John,Four,69,female\r\n22,Reggid,Seven,55,female\r\n23,Herod,Eight,79,male\r\n24,Tiddy Now,Seven,78,male\r\n25,Giff Tow,Seven,88,male\r\n26,Crelea,Seven,79,male\r\n27,Big Nose,Three,81,female\r\n28,Rojj Base,Seven,86,female\r\n29,Tess Played,Seven,55,male\r\n30,Reppy Red,Six,79,female\r\n31,Marry Toeey,Four,88,male\r\n32,Binn Rott,Seven,90,female\r\n33,Kenn Rein,Six,96,female\r\n34,Gain Toe,Seven,69,male\r\n35,Rows Noump,Six,88,female\r\n'}

### Read CSV files

In [3]:
df = pd.read_csv('/content/student.csv')

### Show first 5 rows

In [4]:
df.head(5)

   id        name  class  mark  gender
0   1    John Deo   Four    75  female
1   2    Max Ruin  Three    85    male
2   3      Arnold  Three    55    male
3   4  Krish Star   Four    60  female
4   5   John Mike   Four    60  female

### Show last 5 rows

In [5]:
df.tail(5)

    id         name  class  mark  gender
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      35 non-null     int64
 1   name    35 non-null     object
 2   class   35 non-null     object
 3   mark    35 non-null     int64
 4   gender  35 non-null     object
dtypes: int64(2), object(3)
memory usage: 1.5+ KB

### Access to rows or columns

In [8]:
df.iloc[1]

id               2
name      Max Ruin
class        Three
mark            85
gender        male
Name: 1, dtype: object

In [9]:
df.iloc[:5]

   id        name  class  mark  gender
0   1    John Deo   Four    75  female
1   2    Max Ruin  Three    85    male
2   3      Arnold  Three    55    male
3   4  Krish Star   Four    60  female
4   5   John Mike   Four    60  female

In [10]:
df.iloc[:5,1:3]

         name  class
0    John Deo   Four
1    Max Ruin  Three
2      Arnold  Three
3  Krish Star   Four
4   John Mike   Four

In [11]:
df.loc[:5, 'mark']

0    75
1    85
2    55
3    60
4    60
5    55
Name: mark, dtype: int64

In [12]:
df.loc[:5, ['name', 'mark']]

         name  mark
0    John Deo    75
1    Max Ruin    85
2      Arnold    55
3  Krish Star    60
4   John Mike    60
5   Alex John    55

In [13]:
df['name']

0        John Deo
1        Max Ruin
2          Arnold
3      Krish Star
4       John Mike
5       Alex John
6     My John Rob
7          Asruid
8         Tes Qry
9        Big John
10         Ronald
11          Recky
12            Kty
13           Bigy
14       Tade Row
15          Gimmy
16          Tumyu
17          Honny
18          Tinny
19         Jackly
20     Babby John
21         Reggid
22          Herod
23      Tiddy Now
24       Giff Tow
25         Crelea
26       Big Nose
27      Rojj Base
28    Tess Played
29      Reppy Red
30    Marry Toeey
31      Binn Rott
32      Kenn Rein
33       Gain Toe
34     Rows Noump
Name: name, dtype: object

### Methods

In [14]:
df['mark'].mean()

74.65714285714286

In [15]:
df['mark'].std()

16.401116994139826

In [16]:
df['mark'].sum()

2613

return unique value of column

In [17]:
df['name'].unique()

array(['John Deo', 'Max Ruin', 'Arnold', 'Krish Star', 'John Mike',
       'Alex John', 'My John Rob', 'Asruid', 'Tes Qry', 'Big John',
       'Ronald', 'Recky', 'Kty', 'Bigy', 'Tade Row', 'Gimmy', 'Tumyu',
       'Honny', 'Tinny', 'Jackly', 'Babby John', 'Reggid', 'Herod',
       'Tiddy Now', 'Giff Tow', 'Crelea', 'Big Nose', 'Rojj Base',
       'Tess Played', 'Reppy Red', 'Marry Toeey', 'Binn Rott',
       'Kenn Rein', 'Gain Toe', 'Rows Noump'], dtype=object)

In [18]:
df['gender'].unique()

array(['female', 'male'], dtype=object)

returns the number of unique value in the column

In [19]:
df['gender'].nunique()

2

returns the number of repetitions for each value in the column

In [20]:
df['gender'].value_counts()

male      18
female    17
Name: gender, dtype: int64

In [44]:
df.isna()

     name  class   mark  gender  encode_gender
0   False  False  False   False          False
1   False  False  False   False          False
2   False  False  False   False          False
3   False  False  False   False          False
4   False  False  False   False          False
5   False  False  False   False          False
6   False  False  False   False          False
7   False  False  False   False          False
8   False  False  False   False          False
9   False  False  False   False          False
10  False  False  False   False          False
11  False  False  False   False          False
12  False  False  False   False          False
13  False  False  False   False          False
14  False  False  False   False          False
15  False  False  False   False          False
16  False  False  False   False          False
17  False  False  False   False          False
18  False  False  False   False          False
19  False  False  False   False          False
20  False  False  False   False          False
21  False  False  False   False          False
22  False  False  False   False          False
23  False  False  False   False          False
24  False  False  False   False          False
25  False  False  False   False          False
26  False  False  False   False          False
27  False  False  False   False          False
28  False  False  False   False          False
29  False  False  False   False          False
30  False  False  False   False          False
31  False  False  False   False          False
32  False  False  False   False          False
33  False  False  False   False          False
34  False  False  False   False          False

In [21]:
df.columns

Index(['id', 'name', 'class', 'mark', 'gender'], dtype='object')

In [22]:
df.drop(columns=['id'])

           name  class  mark  gender
0      John Deo   Four    75  female
1      Max Ruin  Three    85    male
2        Arnold  Three    55    male
3    Krish Star   Four    60  female
4     John Mike   Four    60  female
5     Alex John   Four    55    male
6   My John Rob  Fifth    78    male
7        Asruid   Five    85    male
8       Tes Qry    Six    78    male
9      Big John   Four    55  female
10       Ronald    Six    89  female
11        Recky    Six    94  female
12          Kty  Seven    88  female
13         Bigy  Seven    88  female
14     Tade Row   Four    88    male
15        Gimmy   Four    88    male
16        Tumyu    Six    54    male
17        Honny   Five    75    male
18        Tinny   Nine    18    male
19       Jackly   Nine    65  female
20   Babby John   Four    69  female
21       Reggid  Seven    55  female
22        Herod  Eight    79    male
23    Tiddy Now  Seven    78    male
24     Giff Tow  Seven    88    male
25       Crelea  Seven    79    male
26     Big Nose  Three    81  female
27    Rojj Base  Seven    86  female
28  Tess Played  Seven    55    male
29    Reppy Red    Six    79  female
30  Marry Toeey   Four    88    male
31    Binn Rott  Seven    90  female
32    Kenn Rein    Six    96  female
33     Gain Toe  Seven    69    male
34   Rows Noump    Six    88  female

In [23]:
df

    id         name  class  mark  gender
0    1     John Deo   Four    75  female
1    2     Max Ruin  Three    85    male
2    3       Arnold  Three    55    male
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
5    6    Alex John   Four    55    male
6    7  My John Rob  Fifth    78    male
7    8       Asruid   Five    85    male
8    9      Tes Qry    Six    78    male
9   10     Big John   Four    55  female
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
14  15     Tade Row   Four    88    male
15  16        Gimmy   Four    88    male
16  17        Tumyu    Six    54    male
17  18        Honny   Five    75    male
18  19        Tinny   Nine    18    male
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
21  22       Reggid  Seven    55  female
22  23        Herod  Eight    79    male
23  24    Tiddy Now  Seven    78    male
24  25     Giff Tow  Seven    88    male
25  26       Crelea  Seven    79    male
26  27     Big Nose  Three    81  female
27  28    Rojj Base  Seven    86  female
28  29  Tess Played  Seven    55    male
29  30    Reppy Red    Six    79  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

If You want to apply this change, You must set inplace equal to True

In [24]:
df.drop(columns=['id'], inplace=True)

In [25]:
df

           name  class  mark  gender
0      John Deo   Four    75  female
1      Max Ruin  Three    85    male
2        Arnold  Three    55    male
3    Krish Star   Four    60  female
4     John Mike   Four    60  female
5     Alex John   Four    55    male
6   My John Rob  Fifth    78    male
7        Asruid   Five    85    male
8       Tes Qry    Six    78    male
9      Big John   Four    55  female
10       Ronald    Six    89  female
11        Recky    Six    94  female
12          Kty  Seven    88  female
13         Bigy  Seven    88  female
14     Tade Row   Four    88    male
15        Gimmy   Four    88    male
16        Tumyu    Six    54    male
17        Honny   Five    75    male
18        Tinny   Nine    18    male
19       Jackly   Nine    65  female
20   Babby John   Four    69  female
21       Reggid  Seven    55  female
22        Herod  Eight    79    male
23    Tiddy Now  Seven    78    male
24     Giff Tow  Seven    88    male
25       Crelea  Seven    79    male
26     Big Nose  Three    81  female
27    Rojj Base  Seven    86  female
28  Tess Played  Seven    55    male
29    Reppy Red    Six    79  female
30  Marry Toeey   Four    88    male
31    Binn Rott  Seven    90  female
32    Kenn Rein    Six    96  female
33     Gain Toe  Seven    69    male
34   Rows Noump    Six    88  female

### Groupby

With Groupby, You can partition rows into different groups based on column values.

In [26]:
df.groupby('gender').mean()

<ipython-input-26-f7bed15d94f3>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby('gender').mean()

             mark
gender
female  77.529412
male    71.944444

In [27]:
df.groupby('class').mean()

<ipython-input-27-b899bca78c00>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby('class').mean()

            mark
class
Eight  79.000000
Fifth  78.000000
Five   80.000000
Four   70.888889
Nine   41.500000
Seven  77.600000
Six    82.571429
Three  73.666667

### Apply

In [33]:
df['mark'].apply(lambda x:x/100)

0     0.75
1     0.85
2     0.55
3     0.60
4     0.60
5     0.55
6     0.78
7     0.85
8     0.78
9     0.55
10    0.89
11    0.94
12    0.88
13    0.88
14    0.88
15    0.88
16    0.54
17    0.75
18    0.18
19    0.65
20    0.69
21    0.55
22    0.79
23    0.78
24    0.88
25    0.79
26    0.81
27    0.86
28    0.55
29    0.79
30    0.88
31    0.90
32    0.96
33    0.69
34    0.88
Name: mark, dtype: float64

In [36]:
df['gender'].apply(lambda x:0 if x=='male' else 1)

0     1
1     0
2     0
3     1
4     1
5     0
6     0
7     0
8     0
9     1
10    1
11    1
12    1
13    1
14    0
15    0
16    0
17    0
18    0
19    1
20    1
21    1
22    0
23    0
24    0
25    0
26    1
27    1
28    0
29    1
30    0
31    1
32    1
33    0
34    1
Name: gender, dtype: int64

In [37]:
df['encode_gender'] = df['gender'].apply(lambda x:0 if x=='male' else 1)
df.head(5)

         name  class  mark  gender  encode_gender
0    John Deo   Four    75  female              1
1    Max Ruin  Three    85    male              0
2      Arnold  Three    55    male              0
3  Krish Star   Four    60  female              1
4   John Mike   Four    60  female              1

### get_dummies -> convert column into one-hot vector

In [42]:
pd.get_dummies(df['class'])

    Eight  Fifth  Five  Four  Nine  Seven  Six  Three
0       0      0     0     1     0      0    0      0
1       0      0     0     0     0      0    0      1
2       0      0     0     0     0      0    0      1
3       0      0     0     1     0      0    0      0
4       0      0     0     1     0      0    0      0
5       0      0     0     1     0      0    0      0
6       0      1     0     0     0      0    0      0
7       0      0     1     0     0      0    0      0
8       0      0     0     0     0      0    1      0
9       0      0     0     1     0      0    0      0
10      0      0     0     0     0      0    1      0
11      0      0     0     0     0      0    1      0
12      0      0     0     0     0      1    0      0
13      0      0     0     0     0      1    0      0
14      0      0     0     1     0      0    0      0
15      0      0     0     1     0      0    0      0
16      0      0     0     0     0      0    1      0
17      0      0     1     0     0      0    0      0
18      0      0     0     0     1      0    0      0
19      0      0     0     0     1      0    0      0
20      0      0     0     1     0      0    0      0
21      0      0     0     0     0      1    0      0
22      1      0     0     0     0      0    0      0
23      0      0     0     0     0      1    0      0
24      0      0     0     0     0      1    0      0
25      0      0     0     0     0      1    0      0
26      0      0     0     0     0      0    0      1
27      0      0     0     0     0      1    0      0
28      0      0     0     0     0      1    0      0
29      0      0     0     0     0      0    1      0
30      0      0     0     1     0      0    0      0
31      0      0     0     0     0      1    0      0
32      0      0     0     0     0      0    1      0
33      0      0     0     0     0      1    0      0
34      0      0     0     0     0      0    1      0

In [43]:
pd.get_dummies(df['class'], prefix='class')

,class_Eight,class_Fifth,class_Five,class_Four,class_Nine,class_Seven,class_Six,class_Three
0,0,0,0,1,0,0,0,0
1,0,0,0,0,0,0,0,1
2,0,0,0,0,0,0,0,1
3,0,0,0,1,0,0,0,0
4,0,0,0,1,0,0,0,0
5,0,0,0,1,0,0,0,0
6,0,1,0,0,0,0,0,0
7,0,0,1,0,0,0,0,0
8,0,0,0,0,0,0,1,0
9,0,0,0,1,0,0,0,0
10,0,0,0,0,0,0,1,0
11,0,0,0,0,0,0,1,0
12,0,0,0,0,0,1,0,0
13,0,0,0,0,0,1,0,0
14,0,0,0,1,0,0,0,0
15,0,0,0,1,0,0,0,0
16,0,0,0,0,0,0,1,0
17,0,0,1,0,0,0,0,0
18,0,0,0,0,1,0,0,0
19,0,0,0,0,1,0,0,0
20,0,0,0,1,0,0,0,0
21,0,0,0,0,0,1,0,0
22,1,0,0,0,0,0,0,0
23,0,0,0,0,0,1,0,0
24,0,0,0,0,0,1,0,0
25,0,0,0,0,0,1,0,0
26,0,0,0,0,0,0,0,1
27,0,0,0,0,0,1,0,0
28,0,0,0,0,0,1,0,0
29,0,0,0,0,0,0,1,0
30,0,0,0,1,0,0,0,0
31,0,0,0,0,0,1,0,0
32,0,0,0,0,0,0,1,0
33,0,0,0,0,0,1,0,0
34,0,0,0,0,0,0,1,0

In [40]:
pd.get_dummies(df, prefix='class', columns=['class'])

,name,mark,gender,encode_gender,class_Eight,class_Fifth,class_Five,class_Four,class_Nine,class_Seven,class_Six,class_Three
0,John Deo,75,female,1,0,0,0,1,0,0,0,0
1,Max Ruin,85,male,0,0,0,0,0,0,0,0,1
2,Arnold,55,male,0,0,0,0,0,0,0,0,1
3,Krish Star,60,female,1,0,0,0,1,0,0,0,0
4,John Mike,60,female,1,0,0,0,1,0,0,0,0
5,Alex John,55,male,0,0,0,0,1,0,0,0,0
6,My John Rob,78,male,0,0,1,0,0,0,0,0,0
7,Asruid,85,male,0,0,0,1,0,0,0,0,0
8,Tes Qry,78,male,0,0,0,0,0,0,0,1,0
9,Big John,55,female,1,0,0,0,1,0,0,0,0
10,Ronald,89,female,1,0,0,0,0,0,0,1,0
11,Recky,94,female,1,0,0,0,0,0,0,1,0
12,Kty,88,female,1,0,0,0,0,0,1,0,0
13,Bigy,88,female,1,0,0,0,0,0,1,0,0
14,Tade Row,88,male,0,0,0,0,1,0,0,0,0
15,Gimmy,88,male,0,0,0,0,1,0,0,0,0
16,Tumyu,54,male,0,0,0,0,0,0,0,1,0
17,Honny,75,male,0,0,0,1,0,0,0,0,0
18,Tinny,18,male,0,0,0,0,0,1,0,0,0
19,Jackly,65,female,1,0,0,0,0,1,0,0,0
20,Babby John,69,female,1,0,0,0,1,0,0,0,0
21,Reggid,55,female,1,0,0,0,0,0,1,0,0
22,Herod,79,male,0,1,0,0,0,0,0,0,0
23,Tiddy Now,78,male,0,0,0,0,0,0,1,0,0
24,Giff Tow,88,male,0,0,0,0,0,0,1,0,0
25,Crelea,79,male,0,0,0,0,0,0,1,0,0
26,Big Nose,81,female,1,0,0,0,0,0,0,0,1
27,Rojj Base,86,female,1,0,0,0,0,0,1,0,0
28,Tess Played,55,male,0,0,0,0,0,0,1,0,0
29,Reppy Red,79,female,1,0,0,0,0,0,0,1,0
30,Marry Toeey,88,male,0,0,0,0,1,0,0,0,0
31,Binn Rott,90,female,1,0,0,0,0,0,1,0,0
32,Kenn Rein,96,female,1,0,0,0,0,0,0,1,0
33,Gain Toe,69,male,0,0,0,0,0,0,1,0,0
34,Rows Noump,88,female,1,0,0,0,0,0,0,1,0

In [41]:
df.head(5)

         name  class  mark  gender  encode_gender
0    John Deo   Four    75  female              1
1    Max Ruin  Three    85    male              0
2      Arnold  Three    55    male              0
3  Krish Star   Four    60  female              1
4   John Mike   Four    60  female              1

In [54]:
new_row = pd.DataFrame([{'name':'Mmd Hash', 'gender':'male', 'encode_gender':0}])
pd.concat([df,new_row], ignore_index=True)

           name  class  mark  gender  encode_gender
0      John Deo   Four  75.0  female              1
1      Max Ruin  Three  85.0    male              0
2        Arnold  Three  55.0    male              0
3    Krish Star   Four  60.0  female              1
4     John Mike   Four  60.0  female              1
5     Alex John   Four  55.0    male              0
6   My John Rob  Fifth  78.0    male              0
7        Asruid   Five  85.0    male              0
8       Tes Qry    Six  78.0    male              0
9      Big John   Four  55.0  female              1
10       Ronald    Six  89.0  female              1
11        Recky    Six  94.0  female              1
12          Kty  Seven  88.0  female              1
13         Bigy  Seven  88.0  female              1
14     Tade Row   Four  88.0    male              0
15        Gimmy   Four  88.0    male              0
16        Tumyu    Six  54.0    male              0
17        Honny   Five  75.0    male              0
18        Tinny   Nine  18.0    male              0
19       Jackly   Nine  65.0  female              1
20   Babby John   Four  69.0  female              1
21       Reggid  Seven  55.0  female              1
22        Herod  Eight  79.0    male              0
23    Tiddy Now  Seven  78.0    male              0
24     Giff Tow  Seven  88.0    male              0
25       Crelea  Seven  79.0    male              0
26     Big Nose  Three  81.0  female              1
27    Rojj Base  Seven  86.0  female              1
28  Tess Played  Seven  55.0    male              0
29    Reppy Red    Six  79.0  female              1
30  Marry Toeey   Four  88.0    male              0
31    Binn Rott  Seven  90.0  female              1
32    Kenn Rein    Six  96.0  female              1
33     Gain Toe  Seven  69.0    male              0
34   Rows Noump    Six  88.0  female              1
35  Alireza Bin    NaN   NaN    male              0
36     Mmd Hash    NaN   NaN    male              0

In [55]:
df = pd.concat([df,new_row], ignore_index=True)

In [56]:
df.iloc[-1]

name             Mmd Hash
class                 NaN
mark                  NaN
gender               male
encode_gender           0
Name: 36, dtype: object

drop rows with missing values

### Nan Values

In [60]:
df.dropna(0)

<ipython-input-60-f68480620f42>:1: FutureWarning: In a future version of pandas all arguments of DataFrame.dropna will be keyword-only.
  df.dropna(0)

           name  class  mark  gender  encode_gender
0      John Deo   Four  75.0  female              1
1      Max Ruin  Three  85.0    male              0
2        Arnold  Three  55.0    male              0
3    Krish Star   Four  60.0  female              1
4     John Mike   Four  60.0  female              1
5     Alex John   Four  55.0    male              0
6   My John Rob  Fifth  78.0    male              0
7        Asruid   Five  85.0    male              0
8       Tes Qry    Six  78.0    male              0
9      Big John   Four  55.0  female              1
10       Ronald    Six  89.0  female              1
11        Recky    Six  94.0  female              1
12          Kty  Seven  88.0  female              1
13         Bigy  Seven  88.0  female              1
14     Tade Row   Four  88.0    male              0
15        Gimmy   Four  88.0    male              0
16        Tumyu    Six  54.0    male              0
17        Honny   Five  75.0    male              0
18        Tinny   Nine  18.0    male              0
19       Jackly   Nine  65.0  female              1
20   Babby John   Four  69.0  female              1
21       Reggid  Seven  55.0  female              1
22        Herod  Eight  79.0    male              0
23    Tiddy Now  Seven  78.0    male              0
24     Giff Tow  Seven  88.0    male              0
25       Crelea  Seven  79.0    male              0
26     Big Nose  Three  81.0  female              1
27    Rojj Base  Seven  86.0  female              1
28  Tess Played  Seven  55.0    male              0
29    Reppy Red    Six  79.0  female              1
30  Marry Toeey   Four  88.0    male              0
31    Binn Rott  Seven  90.0  female              1
32    Kenn Rein    Six  96.0  female              1
33     Gain Toe  Seven  69.0    male              0
34   Rows Noump    Six  88.0  female              1

drops row if all of the columns value is equal to Nan

In [61]:
df.dropna(axis=0, how='all')

           name  class  mark  gender  encode_gender
0      John Deo   Four  75.0  female              1
1      Max Ruin  Three  85.0    male              0
2        Arnold  Three  55.0    male              0
3    Krish Star   Four  60.0  female              1
4     John Mike   Four  60.0  female              1
5     Alex John   Four  55.0    male              0
6   My John Rob  Fifth  78.0    male              0
7        Asruid   Five  85.0    male              0
8       Tes Qry    Six  78.0    male              0
9      Big John   Four  55.0  female              1
10       Ronald    Six  89.0  female              1
11        Recky    Six  94.0  female              1
12          Kty  Seven  88.0  female              1
13         Bigy  Seven  88.0  female              1
14     Tade Row   Four  88.0    male              0
15        Gimmy   Four  88.0    male              0
16        Tumyu    Six  54.0    male              0
17        Honny   Five  75.0    male              0
18        Tinny   Nine  18.0    male              0
19       Jackly   Nine  65.0  female              1
20   Babby John   Four  69.0  female              1
21       Reggid  Seven  55.0  female              1
22        Herod  Eight  79.0    male              0
23    Tiddy Now  Seven  78.0    male              0
24     Giff Tow  Seven  88.0    male              0
25       Crelea  Seven  79.0    male              0
26     Big Nose  Three  81.0  female              1
27    Rojj Base  Seven  86.0  female              1
28  Tess Played  Seven  55.0    male              0
29    Reppy Red    Six  79.0  female              1
30  Marry Toeey   Four  88.0    male              0
31    Binn Rott  Seven  90.0  female              1
32    Kenn Rein    Six  96.0  female              1
33     Gain Toe  Seven  69.0    male              0
34   Rows Noump    Six  88.0  female              1
35  Alireza Bin    NaN   NaN    male              0
36     Mmd Hash    NaN   NaN    male              0

In [62]:
df['class'].fillna(0)

0      Four
1     Three
2     Three
3      Four
4      Four
5      Four
6     Fifth
7      Five
8       Six
9      Four
10      Six
11      Six
12    Seven
13    Seven
14     Four
15     Four
16      Six
17     Five
18     Nine
19     Nine
20     Four
21    Seven
22    Eight
23    Seven
24    Seven
25    Seven
26    Three
27    Seven
28    Seven
29      Six
30     Four
31    Seven
32      Six
33    Seven
34      Six
35        0
36        0
Name: class, dtype: object

In [63]:
df['class'].fillna('SBU')

0      Four
1     Three
2     Three
3      Four
4      Four
5      Four
6     Fifth
7      Five
8       Six
9      Four
10      Six
11      Six
12    Seven
13    Seven
14     Four
15     Four
16      Six
17     Five
18     Nine
19     Nine
20     Four
21    Seven
22    Eight
23    Seven
24    Seven
25    Seven
26    Three
27    Seven
28    Seven
29      Six
30     Four
31    Seven
32      Six
33    Seven
34      Six
35      SBU
36      SBU
Name: class, dtype: object

In [65]:
df['mark'].fillna(method='ffill')

0     75.0
1     85.0
2     55.0
3     60.0
4     60.0
5     55.0
6     78.0
7     85.0
8     78.0
9     55.0
10    89.0
11    94.0
12    88.0
13    88.0
14    88.0
15    88.0
16    54.0
17    75.0
18    18.0
19    65.0
20    69.0
21    55.0
22    79.0
23    78.0
24    88.0
25    79.0
26    81.0
27    86.0
28    55.0
29    79.0
30    88.0
31    90.0
32    96.0
33    69.0
34    88.0
35    88.0
36    88.0
Name: mark, dtype: float64

In [66]:
df['mark'].fillna(method='bfill')

0     75.0
1     85.0
2     55.0
3     60.0
4     60.0
5     55.0
6     78.0
7     85.0
8     78.0
9     55.0
10    89.0
11    94.0
12    88.0
13    88.0
14    88.0
15    88.0
16    54.0
17    75.0
18    18.0
19    65.0
20    69.0
21    55.0
22    79.0
23    78.0
24    88.0
25    79.0
26    81.0
27    86.0
28    55.0
29    79.0
30    88.0
31    90.0
32    96.0
33    69.0
34    88.0
35     NaN
36     NaN
Name: mark, dtype: float64